export default {
  title: "Reusable Sections",
  name: "reusableSections",
  type: "document",
  fields: [
    {
      title: "Title",
      name: "title",
      description: "What's this page is for?",
      type: "string",
      required: true,
    },
    {
      title: "Sections",
      name: "sections",
      type: "array",
      options: {
        editModal: "fullscreen",
      },
      of: [
        { type: "navigation" },
        { type: "header" },
        { type: "footer" },
        { type: "features" },
        { type: "howItWorks" },
        { type: "testimonial" },
        { type: "newsletter" },
        { type: "pricing" },
        { type: "blog" },
        { type: "portfolio" },
        { type: "faqs" },
        { type: "contact" },
        { type: "callToAction" },
        { type: "team" },
        { type: "stats" },
        { type: "appPromo" },
        { type: "cookies" },
        { type: "logoCloud" },
        { type: "signInSignUp" },
        { type: "textComponent" },
        {
          title: "Reusable Section",
          name: "reusableSection",
          type: "reference",
          to: [{ type: "reusableSections" }],
        },
      ],
    },
  ],
};
