import {
  arrayOfImages,
  arrayOfImageTitleTextAndButton,
  description,
  formLinks,
  mainImage,
  primaryButton,
  secondaryButton,
  title,
  subtitle,
  webriqForms,
  youtubeLink,
  backgroundImage,
} from "../../../common/fields";
import { hideIfVariantIn } from "../../../common/hideIfVariantIn";

export const headerSchema = [
  subtitle(
    hideIfVariantIn([
      "variant_a",
      "variant_b",
      "variant_c",
      "variant_d",
      "variant_e",
      "variant_f",
    ])
  ),
  title(hideIfVariantIn(["variant_f"])),
  arrayOfImages(
    hideIfVariantIn([
      "variant_a",
      "variant_c",
      "variant_d",
      "variant_e",
      "variant_f",
      "variant_g",
      "variant_h",
    ])
  ),
  arrayOfImageTitleTextAndButton(
    hideIfVariantIn([
      "variant_a",
      "variant_b",
      "variant_c",
      "variant_d",
      "variant_e",
      "variant_g",
      "variant_h",
    ])
  ),
  mainImage(
    hideIfVariantIn([
      "variant_b",
      "variant_c",
      "variant_e",
      "variant_f",
      "variant_h",
    ])
  ),
  webriqForms(
    hideIfVariantIn([
      "variant_a",
      "variant_b",
      "variant_c",
      "variant_d",
      "variant_f",
      "variant_g",
      "variant_h",
    ])
  ),
  formLinks(
    hideIfVariantIn([
      "variant_a",
      "variant_b",
      "variant_c",
      "variant_d",
      "variant_f",
      "variant_g",
      "variant_h",
    ])
  ),
  youtubeLink(
    hideIfVariantIn([
      "variant_a",
      "variant_b",
      "variant_d",
      "variant_e",
      "variant_f",
      "variant_g",
    ])
  ),
  description(hideIfVariantIn(["variant_c", "variant_f", "variant_h"])),
  primaryButton(hideIfVariantIn(["variant_f"])),
  secondaryButton(hideIfVariantIn(["variant_f", "variant_g", "variant_h"])),
  backgroundImage(
    hideIfVariantIn([
      "variant_a",
      "variant_b",
      "variant_c",
      "variant_d",
      "variant_e",
      "variant_h",
    ])
  ),
];
